sudo: required

services:
  - docker

script:
  - sudo update.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push aurorafw/archlinux;
    fi
