sudo: required

addons:
  apt:
    packages:
    - bsdtar

services:
  - docker

script:
  - sudo ./update.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    sudo docker push archlinux-armhf;
    fi
